image: gitpod/workspace-full

workspaceLocation: /workspace/learn-hybrid-cloud-exercises/modules/module-10-files

# Commands that will run on workspace start
tasks:
  - name: Start Docker 
    command: docker-compose up -d

# Ports to expose on workspace startup
ports:
  - port: 8081
    onOpen: ignore



